//this source code was auto-generated by tolua#, do not modify it
using System;
using System.Collections.Generic;
using LuaInterface;

public class DelegateFactory
{
	public delegate Delegate DelegateCreate(LuaFunction func, LuaTable self, bool flag);
	public static Dictionary<Type, DelegateCreate> dict = new Dictionary<Type, DelegateCreate>();
	static DelegateFactory factory = new DelegateFactory();

	public static void Init()
	{
		Register();
	}

	public static void Register()
	{
		dict.Clear();
		dict.Add(typeof(System.Action), factory.System_Action);
		dict.Add(typeof(UnityEngine.Events.UnityAction), factory.UnityEngine_Events_UnityAction);
		dict.Add(typeof(System.Predicate<int>), factory.System_Predicate_int);
		dict.Add(typeof(System.Action<int>), factory.System_Action_int);
		dict.Add(typeof(System.Comparison<int>), factory.System_Comparison_int);
		dict.Add(typeof(System.Func<int,int>), factory.System_Func_int_int);
		dict.Add(typeof(RegistFunction), factory.RegistFunction);
		dict.Add(typeof(LuaComponent.OnLoadScriptSuccess), factory.LuaComponent_OnLoadScriptSuccess);
		dict.Add(typeof(LuaComponent.OnLoadScriptFailure), factory.LuaComponent_OnLoadScriptFailure);
		dict.Add(typeof(UnityEngine.Canvas.WillRenderCanvases), factory.UnityEngine_Canvas_WillRenderCanvases);
		dict.Add(typeof(UnityEngine.RectTransform.ReapplyDrivenProperties), factory.UnityEngine_RectTransform_ReapplyDrivenProperties);
		dict.Add(typeof(System.EventHandler<GameFramework.Event.GameEventArgs>), factory.System_EventHandler_GameFramework_Event_GameEventArgs);
		dict.Add(typeof(System.Predicate<GameFramework.ObjectPool.ObjectPoolBase>), factory.System_Predicate_GameFramework_ObjectPool_ObjectPoolBase);
		dict.Add(typeof(GameFramework.Resource.DecryptResourceCallback), factory.GameFramework_Resource_DecryptResourceCallback);
		dict.Add(typeof(GameFramework.Resource.InitResourcesCompleteCallback), factory.GameFramework_Resource_InitResourcesCompleteCallback);
		dict.Add(typeof(GameFramework.Resource.CheckResourcesCompleteCallback), factory.GameFramework_Resource_CheckResourcesCompleteCallback);
		dict.Add(typeof(GameFramework.Resource.ApplyResourcesCompleteCallback), factory.GameFramework_Resource_ApplyResourcesCompleteCallback);
		dict.Add(typeof(GameFramework.Resource.UpdateResourcesCompleteCallback), factory.GameFramework_Resource_UpdateResourcesCompleteCallback);
		dict.Add(typeof(UnityEngine.Camera.CameraCallback), factory.UnityEngine_Camera_CameraCallback);
		dict.Add(typeof(UnityEngine.Application.AdvertisingIdentifierCallback), factory.UnityEngine_Application_AdvertisingIdentifierCallback);
		dict.Add(typeof(UnityEngine.Application.LowMemoryCallback), factory.UnityEngine_Application_LowMemoryCallback);
		dict.Add(typeof(UnityEngine.Application.LogCallback), factory.UnityEngine_Application_LogCallback);
		dict.Add(typeof(System.Action<bool>), factory.System_Action_bool);
		dict.Add(typeof(System.Action<string>), factory.System_Action_string);
		dict.Add(typeof(System.Func<bool>), factory.System_Func_bool);
		dict.Add(typeof(System.Action<UnityEngine.PhysicsScene,Unity.Collections.NativeArray<UnityEngine.ModifiableContactPair>>), factory.System_Action_UnityEngine_PhysicsScene_Unity_Collections_NativeArray_UnityEngine_ModifiableContactPair);
		dict.Add(typeof(UnityEngine.AudioClip.PCMReaderCallback), factory.UnityEngine_AudioClip_PCMReaderCallback);
		dict.Add(typeof(UnityEngine.AudioClip.PCMSetPositionCallback), factory.UnityEngine_AudioClip_PCMSetPositionCallback);
		dict.Add(typeof(System.Action<UnityEngine.AsyncOperation>), factory.System_Action_UnityEngine_AsyncOperation);

		DelegateTraits<System.Action>.Init(factory.System_Action);
		DelegateTraits<UnityEngine.Events.UnityAction>.Init(factory.UnityEngine_Events_UnityAction);
		DelegateTraits<System.Predicate<int>>.Init(factory.System_Predicate_int);
		DelegateTraits<System.Action<int>>.Init(factory.System_Action_int);
		DelegateTraits<System.Comparison<int>>.Init(factory.System_Comparison_int);
		DelegateTraits<System.Func<int,int>>.Init(factory.System_Func_int_int);
		DelegateTraits<RegistFunction>.Init(factory.RegistFunction);
		DelegateTraits<LuaComponent.OnLoadScriptSuccess>.Init(factory.LuaComponent_OnLoadScriptSuccess);
		DelegateTraits<LuaComponent.OnLoadScriptFailure>.Init(factory.LuaComponent_OnLoadScriptFailure);
		DelegateTraits<UnityEngine.Canvas.WillRenderCanvases>.Init(factory.UnityEngine_Canvas_WillRenderCanvases);
		DelegateTraits<UnityEngine.RectTransform.ReapplyDrivenProperties>.Init(factory.UnityEngine_RectTransform_ReapplyDrivenProperties);
		DelegateTraits<System.EventHandler<GameFramework.Event.GameEventArgs>>.Init(factory.System_EventHandler_GameFramework_Event_GameEventArgs);
		DelegateTraits<System.Predicate<GameFramework.ObjectPool.ObjectPoolBase>>.Init(factory.System_Predicate_GameFramework_ObjectPool_ObjectPoolBase);
		DelegateTraits<GameFramework.Resource.DecryptResourceCallback>.Init(factory.GameFramework_Resource_DecryptResourceCallback);
		DelegateTraits<GameFramework.Resource.InitResourcesCompleteCallback>.Init(factory.GameFramework_Resource_InitResourcesCompleteCallback);
		DelegateTraits<GameFramework.Resource.CheckResourcesCompleteCallback>.Init(factory.GameFramework_Resource_CheckResourcesCompleteCallback);
		DelegateTraits<GameFramework.Resource.ApplyResourcesCompleteCallback>.Init(factory.GameFramework_Resource_ApplyResourcesCompleteCallback);
		DelegateTraits<GameFramework.Resource.UpdateResourcesCompleteCallback>.Init(factory.GameFramework_Resource_UpdateResourcesCompleteCallback);
		DelegateTraits<UnityEngine.Camera.CameraCallback>.Init(factory.UnityEngine_Camera_CameraCallback);
		DelegateTraits<UnityEngine.Application.AdvertisingIdentifierCallback>.Init(factory.UnityEngine_Application_AdvertisingIdentifierCallback);
		DelegateTraits<UnityEngine.Application.LowMemoryCallback>.Init(factory.UnityEngine_Application_LowMemoryCallback);
		DelegateTraits<UnityEngine.Application.LogCallback>.Init(factory.UnityEngine_Application_LogCallback);
		DelegateTraits<System.Action<bool>>.Init(factory.System_Action_bool);
		DelegateTraits<System.Action<string>>.Init(factory.System_Action_string);
		DelegateTraits<System.Func<bool>>.Init(factory.System_Func_bool);
		DelegateTraits<System.Action<UnityEngine.PhysicsScene,Unity.Collections.NativeArray<UnityEngine.ModifiableContactPair>>>.Init(factory.System_Action_UnityEngine_PhysicsScene_Unity_Collections_NativeArray_UnityEngine_ModifiableContactPair);
		DelegateTraits<UnityEngine.AudioClip.PCMReaderCallback>.Init(factory.UnityEngine_AudioClip_PCMReaderCallback);
		DelegateTraits<UnityEngine.AudioClip.PCMSetPositionCallback>.Init(factory.UnityEngine_AudioClip_PCMSetPositionCallback);
		DelegateTraits<System.Action<UnityEngine.AsyncOperation>>.Init(factory.System_Action_UnityEngine_AsyncOperation);

		TypeTraits<System.Action>.Init(factory.Check_System_Action);
		TypeTraits<UnityEngine.Events.UnityAction>.Init(factory.Check_UnityEngine_Events_UnityAction);
		TypeTraits<System.Predicate<int>>.Init(factory.Check_System_Predicate_int);
		TypeTraits<System.Action<int>>.Init(factory.Check_System_Action_int);
		TypeTraits<System.Comparison<int>>.Init(factory.Check_System_Comparison_int);
		TypeTraits<System.Func<int,int>>.Init(factory.Check_System_Func_int_int);
		TypeTraits<RegistFunction>.Init(factory.Check_RegistFunction);
		TypeTraits<LuaComponent.OnLoadScriptSuccess>.Init(factory.Check_LuaComponent_OnLoadScriptSuccess);
		TypeTraits<LuaComponent.OnLoadScriptFailure>.Init(factory.Check_LuaComponent_OnLoadScriptFailure);
		TypeTraits<UnityEngine.Canvas.WillRenderCanvases>.Init(factory.Check_UnityEngine_Canvas_WillRenderCanvases);
		TypeTraits<UnityEngine.RectTransform.ReapplyDrivenProperties>.Init(factory.Check_UnityEngine_RectTransform_ReapplyDrivenProperties);
		TypeTraits<System.EventHandler<GameFramework.Event.GameEventArgs>>.Init(factory.Check_System_EventHandler_GameFramework_Event_GameEventArgs);
		TypeTraits<System.Predicate<GameFramework.ObjectPool.ObjectPoolBase>>.Init(factory.Check_System_Predicate_GameFramework_ObjectPool_ObjectPoolBase);
		TypeTraits<GameFramework.Resource.DecryptResourceCallback>.Init(factory.Check_GameFramework_Resource_DecryptResourceCallback);
		TypeTraits<GameFramework.Resource.InitResourcesCompleteCallback>.Init(factory.Check_GameFramework_Resource_InitResourcesCompleteCallback);
		TypeTraits<GameFramework.Resource.CheckResourcesCompleteCallback>.Init(factory.Check_GameFramework_Resource_CheckResourcesCompleteCallback);
		TypeTraits<GameFramework.Resource.ApplyResourcesCompleteCallback>.Init(factory.Check_GameFramework_Resource_ApplyResourcesCompleteCallback);
		TypeTraits<GameFramework.Resource.UpdateResourcesCompleteCallback>.Init(factory.Check_GameFramework_Resource_UpdateResourcesCompleteCallback);
		TypeTraits<UnityEngine.Camera.CameraCallback>.Init(factory.Check_UnityEngine_Camera_CameraCallback);
		TypeTraits<UnityEngine.Application.AdvertisingIdentifierCallback>.Init(factory.Check_UnityEngine_Application_AdvertisingIdentifierCallback);
		TypeTraits<UnityEngine.Application.LowMemoryCallback>.Init(factory.Check_UnityEngine_Application_LowMemoryCallback);
		TypeTraits<UnityEngine.Application.LogCallback>.Init(factory.Check_UnityEngine_Application_LogCallback);
		TypeTraits<System.Action<bool>>.Init(factory.Check_System_Action_bool);
		TypeTraits<System.Action<string>>.Init(factory.Check_System_Action_string);
		TypeTraits<System.Func<bool>>.Init(factory.Check_System_Func_bool);
		TypeTraits<System.Action<UnityEngine.PhysicsScene,Unity.Collections.NativeArray<UnityEngine.ModifiableContactPair>>>.Init(factory.Check_System_Action_UnityEngine_PhysicsScene_Unity_Collections_NativeArray_UnityEngine_ModifiableContactPair);
		TypeTraits<UnityEngine.AudioClip.PCMReaderCallback>.Init(factory.Check_UnityEngine_AudioClip_PCMReaderCallback);
		TypeTraits<UnityEngine.AudioClip.PCMSetPositionCallback>.Init(factory.Check_UnityEngine_AudioClip_PCMSetPositionCallback);
		TypeTraits<System.Action<UnityEngine.AsyncOperation>>.Init(factory.Check_System_Action_UnityEngine_AsyncOperation);

		StackTraits<System.Action>.Push = factory.Push_System_Action;
		StackTraits<UnityEngine.Events.UnityAction>.Push = factory.Push_UnityEngine_Events_UnityAction;
		StackTraits<System.Predicate<int>>.Push = factory.Push_System_Predicate_int;
		StackTraits<System.Action<int>>.Push = factory.Push_System_Action_int;
		StackTraits<System.Comparison<int>>.Push = factory.Push_System_Comparison_int;
		StackTraits<System.Func<int,int>>.Push = factory.Push_System_Func_int_int;
		StackTraits<RegistFunction>.Push = factory.Push_RegistFunction;
		StackTraits<LuaComponent.OnLoadScriptSuccess>.Push = factory.Push_LuaComponent_OnLoadScriptSuccess;
		StackTraits<LuaComponent.OnLoadScriptFailure>.Push = factory.Push_LuaComponent_OnLoadScriptFailure;
		StackTraits<UnityEngine.Canvas.WillRenderCanvases>.Push = factory.Push_UnityEngine_Canvas_WillRenderCanvases;
		StackTraits<UnityEngine.RectTransform.ReapplyDrivenProperties>.Push = factory.Push_UnityEngine_RectTransform_ReapplyDrivenProperties;
		StackTraits<System.EventHandler<GameFramework.Event.GameEventArgs>>.Push = factory.Push_System_EventHandler_GameFramework_Event_GameEventArgs;
		StackTraits<System.Predicate<GameFramework.ObjectPool.ObjectPoolBase>>.Push = factory.Push_System_Predicate_GameFramework_ObjectPool_ObjectPoolBase;
		StackTraits<GameFramework.Resource.DecryptResourceCallback>.Push = factory.Push_GameFramework_Resource_DecryptResourceCallback;
		StackTraits<GameFramework.Resource.InitResourcesCompleteCallback>.Push = factory.Push_GameFramework_Resource_InitResourcesCompleteCallback;
		StackTraits<GameFramework.Resource.CheckResourcesCompleteCallback>.Push = factory.Push_GameFramework_Resource_CheckResourcesCompleteCallback;
		StackTraits<GameFramework.Resource.ApplyResourcesCompleteCallback>.Push = factory.Push_GameFramework_Resource_ApplyResourcesCompleteCallback;
		StackTraits<GameFramework.Resource.UpdateResourcesCompleteCallback>.Push = factory.Push_GameFramework_Resource_UpdateResourcesCompleteCallback;
		StackTraits<UnityEngine.Camera.CameraCallback>.Push = factory.Push_UnityEngine_Camera_CameraCallback;
		StackTraits<UnityEngine.Application.AdvertisingIdentifierCallback>.Push = factory.Push_UnityEngine_Application_AdvertisingIdentifierCallback;
		StackTraits<UnityEngine.Application.LowMemoryCallback>.Push = factory.Push_UnityEngine_Application_LowMemoryCallback;
		StackTraits<UnityEngine.Application.LogCallback>.Push = factory.Push_UnityEngine_Application_LogCallback;
		StackTraits<System.Action<bool>>.Push = factory.Push_System_Action_bool;
		StackTraits<System.Action<string>>.Push = factory.Push_System_Action_string;
		StackTraits<System.Func<bool>>.Push = factory.Push_System_Func_bool;
		StackTraits<System.Action<UnityEngine.PhysicsScene,Unity.Collections.NativeArray<UnityEngine.ModifiableContactPair>>>.Push = factory.Push_System_Action_UnityEngine_PhysicsScene_Unity_Collections_NativeArray_UnityEngine_ModifiableContactPair;
		StackTraits<UnityEngine.AudioClip.PCMReaderCallback>.Push = factory.Push_UnityEngine_AudioClip_PCMReaderCallback;
		StackTraits<UnityEngine.AudioClip.PCMSetPositionCallback>.Push = factory.Push_UnityEngine_AudioClip_PCMSetPositionCallback;
		StackTraits<System.Action<UnityEngine.AsyncOperation>>.Push = factory.Push_System_Action_UnityEngine_AsyncOperation;
	}
    
    public static Delegate CreateDelegate(Type t, LuaFunction func = null)
    {
        DelegateCreate Create = null;

        if (!dict.TryGetValue(t, out Create))
        {
            throw new LuaException(string.Format("Delegate {0} not register", LuaMisc.GetTypeName(t)));            
        }

        if (func != null)
        {
            LuaState state = func.GetLuaState();
            LuaDelegate target = state.GetLuaDelegate(func);
            
            if (target != null)
            {
                return Delegate.CreateDelegate(t, target, target.method);
            }  
            else
            {
                Delegate d = Create(func, null, false);
                target = d.Target as LuaDelegate;
                state.AddLuaDelegate(target, func);
                return d;
            }       
        }

        return Create(null, null, false);        
    }
    
    public static Delegate CreateDelegate(Type t, LuaFunction func, LuaTable self)
    {
        DelegateCreate Create = null;

        if (!dict.TryGetValue(t, out Create))
        {
            throw new LuaException(string.Format("Delegate {0} not register", LuaMisc.GetTypeName(t)));
        }

        if (func != null)
        {
            LuaState state = func.GetLuaState();
            LuaDelegate target = state.GetLuaDelegate(func, self);

            if (target != null)
            {
                return Delegate.CreateDelegate(t, target, target.method);
            }
            else
            {
                Delegate d = Create(func, self, true);
                target = d.Target as LuaDelegate;
                state.AddLuaDelegate(target, func, self);
                return d;
            }
        }

        return Create(null, null, true);
    }
    
    public static Delegate RemoveDelegate(Delegate obj, LuaFunction func)
    {        
        Delegate[] ds = obj.GetInvocationList();

        for (int i = 0; i < ds.Length; i++)
        {
            LuaDelegate ld = ds[i].Target as LuaDelegate;

            if (ld != null && ld.func == func)
            {
                obj = Delegate.Remove(obj, ds[i]);
                if (obj != null) obj.AddRef();
                break;
            }
        }

        return obj;
    }
    
    public static Delegate RemoveDelegate(Delegate obj, Delegate dg)
    {
        LuaDelegate remove = dg.Target as LuaDelegate;

        if (remove == null)
        {
            obj = Delegate.Remove(obj, dg);
            return obj;
        }
        
        Delegate[] ds = obj.GetInvocationList();        

        for (int i = 0; i < ds.Length; i++)
        {
            LuaDelegate ld = ds[i].Target as LuaDelegate;

            if (ld != null && ld == remove)
            {
                obj = Delegate.Remove(obj, ds[i]);
                if (obj != null) obj.AddRef();                
                break;
            }
        }

        return obj;
    }

	class System_Action_Event : LuaDelegate
	{
		public System_Action_Event(LuaFunction func) : base(func) { }
		public System_Action_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call()
		{
			func.Call();
		}

		public void CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			func.EndPCall();
		}
	}

	public System.Action System_Action(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action fn = delegate() { };
			return fn;
		}

		if(!flag)
		{
			System_Action_Event target = new System_Action_Event(func);
			System.Action d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_Event target = new System_Action_Event(func, self);
			System.Action d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_System_Action(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType<System.Action>(L, pos);
	}

	void Push_System_Action(IntPtr L, System.Action o)
	{
		ToLua.Push(L, o);
	}

	class UnityEngine_Events_UnityAction_Event : LuaDelegate
	{
		public UnityEngine_Events_UnityAction_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Events_UnityAction_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call()
		{
			func.Call();
		}

		public void CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			func.EndPCall();
		}
	}

	public UnityEngine.Events.UnityAction UnityEngine_Events_UnityAction(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Events.UnityAction fn = delegate() { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Events_UnityAction_Event target = new UnityEngine_Events_UnityAction_Event(func);
			UnityEngine.Events.UnityAction d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Events_UnityAction_Event target = new UnityEngine_Events_UnityAction_Event(func, self);
			UnityEngine.Events.UnityAction d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_UnityEngine_Events_UnityAction(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType<UnityEngine.Events.UnityAction>(L, pos);
	}

	void Push_UnityEngine_Events_UnityAction(IntPtr L, UnityEngine.Events.UnityAction o)
	{
		ToLua.Push(L, o);
	}

	class System_Predicate_int_Event : LuaDelegate
	{
		public System_Predicate_int_Event(LuaFunction func) : base(func) { }
		public System_Predicate_int_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public bool Call(int param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			bool ret = func.CheckBoolean();
			func.EndPCall();
			return ret;
		}

		public bool CallWithSelf(int param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			bool ret = func.CheckBoolean();
			func.EndPCall();
			return ret;
		}
	}

	public System.Predicate<int> System_Predicate_int(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Predicate<int> fn = delegate(int param0) { return false; };
			return fn;
		}

		if(!flag)
		{
			System_Predicate_int_Event target = new System_Predicate_int_Event(func);
			System.Predicate<int> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Predicate_int_Event target = new System_Predicate_int_Event(func, self);
			System.Predicate<int> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_System_Predicate_int(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType<System.Predicate<int>>(L, pos);
	}

	void Push_System_Predicate_int(IntPtr L, System.Predicate<int> o)
	{
		ToLua.Push(L, o);
	}

	class System_Action_int_Event : LuaDelegate
	{
		public System_Action_int_Event(LuaFunction func) : base(func) { }
		public System_Action_int_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(int param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(int param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public System.Action<int> System_Action_int(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<int> fn = delegate(int param0) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_int_Event target = new System_Action_int_Event(func);
			System.Action<int> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_int_Event target = new System_Action_int_Event(func, self);
			System.Action<int> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_System_Action_int(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType<System.Action<int>>(L, pos);
	}

	void Push_System_Action_int(IntPtr L, System.Action<int> o)
	{
		ToLua.Push(L, o);
	}

	class System_Comparison_int_Event : LuaDelegate
	{
		public System_Comparison_int_Event(LuaFunction func) : base(func) { }
		public System_Comparison_int_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public int Call(int param0, int param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			int ret = (int)func.CheckInteger();
			func.EndPCall();
			return ret;
		}

		public int CallWithSelf(int param0, int param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			int ret = (int)func.CheckInteger();
			func.EndPCall();
			return ret;
		}
	}

	public System.Comparison<int> System_Comparison_int(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Comparison<int> fn = delegate(int param0, int param1) { return 0; };
			return fn;
		}

		if(!flag)
		{
			System_Comparison_int_Event target = new System_Comparison_int_Event(func);
			System.Comparison<int> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Comparison_int_Event target = new System_Comparison_int_Event(func, self);
			System.Comparison<int> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_System_Comparison_int(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType<System.Comparison<int>>(L, pos);
	}

	void Push_System_Comparison_int(IntPtr L, System.Comparison<int> o)
	{
		ToLua.Push(L, o);
	}

	class System_Func_int_int_Event : LuaDelegate
	{
		public System_Func_int_int_Event(LuaFunction func) : base(func) { }
		public System_Func_int_int_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public int Call(int param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			int ret = (int)func.CheckInteger();
			func.EndPCall();
			return ret;
		}

		public int CallWithSelf(int param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			int ret = (int)func.CheckInteger();
			func.EndPCall();
			return ret;
		}
	}

	public System.Func<int,int> System_Func_int_int(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Func<int,int> fn = delegate(int param0) { return 0; };
			return fn;
		}

		if(!flag)
		{
			System_Func_int_int_Event target = new System_Func_int_int_Event(func);
			System.Func<int,int> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Func_int_int_Event target = new System_Func_int_int_Event(func, self);
			System.Func<int,int> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_System_Func_int_int(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType<System.Func<int,int>>(L, pos);
	}

	void Push_System_Func_int_int(IntPtr L, System.Func<int,int> o)
	{
		ToLua.Push(L, o);
	}

	class RegistFunction_Event : LuaDelegate
	{
		public RegistFunction_Event(LuaFunction func) : base(func) { }
		public RegistFunction_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public object Call(object param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			object ret = func.CheckVariant();
			func.EndPCall();
			return ret;
		}

		public object CallWithSelf(object param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			object ret = func.CheckVariant();
			func.EndPCall();
			return ret;
		}
	}

	public RegistFunction RegistFunction(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			RegistFunction fn = delegate(object param0) { return null; };
			return fn;
		}

		if(!flag)
		{
			RegistFunction_Event target = new RegistFunction_Event(func);
			RegistFunction d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			RegistFunction_Event target = new RegistFunction_Event(func, self);
			RegistFunction d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_RegistFunction(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType<RegistFunction>(L, pos);
	}

	void Push_RegistFunction(IntPtr L, RegistFunction o)
	{
		ToLua.Push(L, o);
	}

	class LuaComponent_OnLoadScriptSuccess_Event : LuaDelegate
	{
		public LuaComponent_OnLoadScriptSuccess_Event(LuaFunction func) : base(func) { }
		public LuaComponent_OnLoadScriptSuccess_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(string param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(string param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public LuaComponent.OnLoadScriptSuccess LuaComponent_OnLoadScriptSuccess(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			LuaComponent.OnLoadScriptSuccess fn = delegate(string param0) { };
			return fn;
		}

		if(!flag)
		{
			LuaComponent_OnLoadScriptSuccess_Event target = new LuaComponent_OnLoadScriptSuccess_Event(func);
			LuaComponent.OnLoadScriptSuccess d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			LuaComponent_OnLoadScriptSuccess_Event target = new LuaComponent_OnLoadScriptSuccess_Event(func, self);
			LuaComponent.OnLoadScriptSuccess d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_LuaComponent_OnLoadScriptSuccess(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType<LuaComponent.OnLoadScriptSuccess>(L, pos);
	}

	void Push_LuaComponent_OnLoadScriptSuccess(IntPtr L, LuaComponent.OnLoadScriptSuccess o)
	{
		ToLua.Push(L, o);
	}

	class LuaComponent_OnLoadScriptFailure_Event : LuaDelegate
	{
		public LuaComponent_OnLoadScriptFailure_Event(LuaFunction func) : base(func) { }
		public LuaComponent_OnLoadScriptFailure_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(string param0, GameFramework.Resource.LoadResourceStatus param1, string param2)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(string param0, GameFramework.Resource.LoadResourceStatus param1, string param2)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			func.EndPCall();
		}
	}

	public LuaComponent.OnLoadScriptFailure LuaComponent_OnLoadScriptFailure(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			LuaComponent.OnLoadScriptFailure fn = delegate(string param0, GameFramework.Resource.LoadResourceStatus param1, string param2) { };
			return fn;
		}

		if(!flag)
		{
			LuaComponent_OnLoadScriptFailure_Event target = new LuaComponent_OnLoadScriptFailure_Event(func);
			LuaComponent.OnLoadScriptFailure d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			LuaComponent_OnLoadScriptFailure_Event target = new LuaComponent_OnLoadScriptFailure_Event(func, self);
			LuaComponent.OnLoadScriptFailure d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_LuaComponent_OnLoadScriptFailure(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType<LuaComponent.OnLoadScriptFailure>(L, pos);
	}

	void Push_LuaComponent_OnLoadScriptFailure(IntPtr L, LuaComponent.OnLoadScriptFailure o)
	{
		ToLua.Push(L, o);
	}

	class UnityEngine_Canvas_WillRenderCanvases_Event : LuaDelegate
	{
		public UnityEngine_Canvas_WillRenderCanvases_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Canvas_WillRenderCanvases_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call()
		{
			func.Call();
		}

		public void CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			func.EndPCall();
		}
	}

	public UnityEngine.Canvas.WillRenderCanvases UnityEngine_Canvas_WillRenderCanvases(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Canvas.WillRenderCanvases fn = delegate() { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Canvas_WillRenderCanvases_Event target = new UnityEngine_Canvas_WillRenderCanvases_Event(func);
			UnityEngine.Canvas.WillRenderCanvases d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Canvas_WillRenderCanvases_Event target = new UnityEngine_Canvas_WillRenderCanvases_Event(func, self);
			UnityEngine.Canvas.WillRenderCanvases d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_UnityEngine_Canvas_WillRenderCanvases(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType<UnityEngine.Canvas.WillRenderCanvases>(L, pos);
	}

	void Push_UnityEngine_Canvas_WillRenderCanvases(IntPtr L, UnityEngine.Canvas.WillRenderCanvases o)
	{
		ToLua.Push(L, o);
	}

	class UnityEngine_RectTransform_ReapplyDrivenProperties_Event : LuaDelegate
	{
		public UnityEngine_RectTransform_ReapplyDrivenProperties_Event(LuaFunction func) : base(func) { }
		public UnityEngine_RectTransform_ReapplyDrivenProperties_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.RectTransform param0)
		{
			func.BeginPCall();
			func.PushSealed(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.RectTransform param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushSealed(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public UnityEngine.RectTransform.ReapplyDrivenProperties UnityEngine_RectTransform_ReapplyDrivenProperties(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.RectTransform.ReapplyDrivenProperties fn = delegate(UnityEngine.RectTransform param0) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_RectTransform_ReapplyDrivenProperties_Event target = new UnityEngine_RectTransform_ReapplyDrivenProperties_Event(func);
			UnityEngine.RectTransform.ReapplyDrivenProperties d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_RectTransform_ReapplyDrivenProperties_Event target = new UnityEngine_RectTransform_ReapplyDrivenProperties_Event(func, self);
			UnityEngine.RectTransform.ReapplyDrivenProperties d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_UnityEngine_RectTransform_ReapplyDrivenProperties(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType<UnityEngine.RectTransform.ReapplyDrivenProperties>(L, pos);
	}

	void Push_UnityEngine_RectTransform_ReapplyDrivenProperties(IntPtr L, UnityEngine.RectTransform.ReapplyDrivenProperties o)
	{
		ToLua.Push(L, o);
	}

	class System_EventHandler_GameFramework_Event_GameEventArgs_Event : LuaDelegate
	{
		public System_EventHandler_GameFramework_Event_GameEventArgs_Event(LuaFunction func) : base(func) { }
		public System_EventHandler_GameFramework_Event_GameEventArgs_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(object param0, GameFramework.Event.GameEventArgs param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PushObject(param1);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(object param0, GameFramework.Event.GameEventArgs param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PushObject(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public System.EventHandler<GameFramework.Event.GameEventArgs> System_EventHandler_GameFramework_Event_GameEventArgs(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.EventHandler<GameFramework.Event.GameEventArgs> fn = delegate(object param0, GameFramework.Event.GameEventArgs param1) { };
			return fn;
		}

		if(!flag)
		{
			System_EventHandler_GameFramework_Event_GameEventArgs_Event target = new System_EventHandler_GameFramework_Event_GameEventArgs_Event(func);
			System.EventHandler<GameFramework.Event.GameEventArgs> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_EventHandler_GameFramework_Event_GameEventArgs_Event target = new System_EventHandler_GameFramework_Event_GameEventArgs_Event(func, self);
			System.EventHandler<GameFramework.Event.GameEventArgs> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_System_EventHandler_GameFramework_Event_GameEventArgs(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType<System.EventHandler<GameFramework.Event.GameEventArgs>>(L, pos);
	}

	void Push_System_EventHandler_GameFramework_Event_GameEventArgs(IntPtr L, System.EventHandler<GameFramework.Event.GameEventArgs> o)
	{
		ToLua.Push(L, o);
	}

	class System_Predicate_GameFramework_ObjectPool_ObjectPoolBase_Event : LuaDelegate
	{
		public System_Predicate_GameFramework_ObjectPool_ObjectPoolBase_Event(LuaFunction func) : base(func) { }
		public System_Predicate_GameFramework_ObjectPool_ObjectPoolBase_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public bool Call(GameFramework.ObjectPool.ObjectPoolBase param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			bool ret = func.CheckBoolean();
			func.EndPCall();
			return ret;
		}

		public bool CallWithSelf(GameFramework.ObjectPool.ObjectPoolBase param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PCall();
			bool ret = func.CheckBoolean();
			func.EndPCall();
			return ret;
		}
	}

	public System.Predicate<GameFramework.ObjectPool.ObjectPoolBase> System_Predicate_GameFramework_ObjectPool_ObjectPoolBase(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Predicate<GameFramework.ObjectPool.ObjectPoolBase> fn = delegate(GameFramework.ObjectPool.ObjectPoolBase param0) { return false; };
			return fn;
		}

		if(!flag)
		{
			System_Predicate_GameFramework_ObjectPool_ObjectPoolBase_Event target = new System_Predicate_GameFramework_ObjectPool_ObjectPoolBase_Event(func);
			System.Predicate<GameFramework.ObjectPool.ObjectPoolBase> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Predicate_GameFramework_ObjectPool_ObjectPoolBase_Event target = new System_Predicate_GameFramework_ObjectPool_ObjectPoolBase_Event(func, self);
			System.Predicate<GameFramework.ObjectPool.ObjectPoolBase> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_System_Predicate_GameFramework_ObjectPool_ObjectPoolBase(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType<System.Predicate<GameFramework.ObjectPool.ObjectPoolBase>>(L, pos);
	}

	void Push_System_Predicate_GameFramework_ObjectPool_ObjectPoolBase(IntPtr L, System.Predicate<GameFramework.ObjectPool.ObjectPoolBase> o)
	{
		ToLua.Push(L, o);
	}

	class GameFramework_Resource_DecryptResourceCallback_Event : LuaDelegate
	{
		public GameFramework_Resource_DecryptResourceCallback_Event(LuaFunction func) : base(func) { }
		public GameFramework_Resource_DecryptResourceCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(byte[] param0, int param1, int param2, string param3, string param4, string param5, bool param6, string param7, byte param8, int param9, int param10)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.Push(param3);
			func.Push(param4);
			func.Push(param5);
			func.Push(param6);
			func.Push(param7);
			func.Push(param8);
			func.Push(param9);
			func.Push(param10);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(byte[] param0, int param1, int param2, string param3, string param4, string param5, bool param6, string param7, byte param8, int param9, int param10)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.Push(param3);
			func.Push(param4);
			func.Push(param5);
			func.Push(param6);
			func.Push(param7);
			func.Push(param8);
			func.Push(param9);
			func.Push(param10);
			func.PCall();
			func.EndPCall();
		}
	}

	public GameFramework.Resource.DecryptResourceCallback GameFramework_Resource_DecryptResourceCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			GameFramework.Resource.DecryptResourceCallback fn = delegate(byte[] param0, int param1, int param2, string param3, string param4, string param5, bool param6, string param7, byte param8, int param9, int param10) { };
			return fn;
		}

		if(!flag)
		{
			GameFramework_Resource_DecryptResourceCallback_Event target = new GameFramework_Resource_DecryptResourceCallback_Event(func);
			GameFramework.Resource.DecryptResourceCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			GameFramework_Resource_DecryptResourceCallback_Event target = new GameFramework_Resource_DecryptResourceCallback_Event(func, self);
			GameFramework.Resource.DecryptResourceCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_GameFramework_Resource_DecryptResourceCallback(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType<GameFramework.Resource.DecryptResourceCallback>(L, pos);
	}

	void Push_GameFramework_Resource_DecryptResourceCallback(IntPtr L, GameFramework.Resource.DecryptResourceCallback o)
	{
		ToLua.Push(L, o);
	}

	class GameFramework_Resource_InitResourcesCompleteCallback_Event : LuaDelegate
	{
		public GameFramework_Resource_InitResourcesCompleteCallback_Event(LuaFunction func) : base(func) { }
		public GameFramework_Resource_InitResourcesCompleteCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call()
		{
			func.Call();
		}

		public void CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			func.EndPCall();
		}
	}

	public GameFramework.Resource.InitResourcesCompleteCallback GameFramework_Resource_InitResourcesCompleteCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			GameFramework.Resource.InitResourcesCompleteCallback fn = delegate() { };
			return fn;
		}

		if(!flag)
		{
			GameFramework_Resource_InitResourcesCompleteCallback_Event target = new GameFramework_Resource_InitResourcesCompleteCallback_Event(func);
			GameFramework.Resource.InitResourcesCompleteCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			GameFramework_Resource_InitResourcesCompleteCallback_Event target = new GameFramework_Resource_InitResourcesCompleteCallback_Event(func, self);
			GameFramework.Resource.InitResourcesCompleteCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_GameFramework_Resource_InitResourcesCompleteCallback(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType<GameFramework.Resource.InitResourcesCompleteCallback>(L, pos);
	}

	void Push_GameFramework_Resource_InitResourcesCompleteCallback(IntPtr L, GameFramework.Resource.InitResourcesCompleteCallback o)
	{
		ToLua.Push(L, o);
	}

	class GameFramework_Resource_CheckResourcesCompleteCallback_Event : LuaDelegate
	{
		public GameFramework_Resource_CheckResourcesCompleteCallback_Event(LuaFunction func) : base(func) { }
		public GameFramework_Resource_CheckResourcesCompleteCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(int param0, int param1, int param2, long param3, long param4)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.Push(param3);
			func.Push(param4);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(int param0, int param1, int param2, long param3, long param4)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.Push(param3);
			func.Push(param4);
			func.PCall();
			func.EndPCall();
		}
	}

	public GameFramework.Resource.CheckResourcesCompleteCallback GameFramework_Resource_CheckResourcesCompleteCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			GameFramework.Resource.CheckResourcesCompleteCallback fn = delegate(int param0, int param1, int param2, long param3, long param4) { };
			return fn;
		}

		if(!flag)
		{
			GameFramework_Resource_CheckResourcesCompleteCallback_Event target = new GameFramework_Resource_CheckResourcesCompleteCallback_Event(func);
			GameFramework.Resource.CheckResourcesCompleteCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			GameFramework_Resource_CheckResourcesCompleteCallback_Event target = new GameFramework_Resource_CheckResourcesCompleteCallback_Event(func, self);
			GameFramework.Resource.CheckResourcesCompleteCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_GameFramework_Resource_CheckResourcesCompleteCallback(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType<GameFramework.Resource.CheckResourcesCompleteCallback>(L, pos);
	}

	void Push_GameFramework_Resource_CheckResourcesCompleteCallback(IntPtr L, GameFramework.Resource.CheckResourcesCompleteCallback o)
	{
		ToLua.Push(L, o);
	}

	class GameFramework_Resource_ApplyResourcesCompleteCallback_Event : LuaDelegate
	{
		public GameFramework_Resource_ApplyResourcesCompleteCallback_Event(LuaFunction func) : base(func) { }
		public GameFramework_Resource_ApplyResourcesCompleteCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(string param0, bool param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(string param0, bool param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public GameFramework.Resource.ApplyResourcesCompleteCallback GameFramework_Resource_ApplyResourcesCompleteCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			GameFramework.Resource.ApplyResourcesCompleteCallback fn = delegate(string param0, bool param1) { };
			return fn;
		}

		if(!flag)
		{
			GameFramework_Resource_ApplyResourcesCompleteCallback_Event target = new GameFramework_Resource_ApplyResourcesCompleteCallback_Event(func);
			GameFramework.Resource.ApplyResourcesCompleteCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			GameFramework_Resource_ApplyResourcesCompleteCallback_Event target = new GameFramework_Resource_ApplyResourcesCompleteCallback_Event(func, self);
			GameFramework.Resource.ApplyResourcesCompleteCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_GameFramework_Resource_ApplyResourcesCompleteCallback(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType<GameFramework.Resource.ApplyResourcesCompleteCallback>(L, pos);
	}

	void Push_GameFramework_Resource_ApplyResourcesCompleteCallback(IntPtr L, GameFramework.Resource.ApplyResourcesCompleteCallback o)
	{
		ToLua.Push(L, o);
	}

	class GameFramework_Resource_UpdateResourcesCompleteCallback_Event : LuaDelegate
	{
		public GameFramework_Resource_UpdateResourcesCompleteCallback_Event(LuaFunction func) : base(func) { }
		public GameFramework_Resource_UpdateResourcesCompleteCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(GameFramework.Resource.IResourceGroup param0, bool param1)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(GameFramework.Resource.IResourceGroup param0, bool param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public GameFramework.Resource.UpdateResourcesCompleteCallback GameFramework_Resource_UpdateResourcesCompleteCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			GameFramework.Resource.UpdateResourcesCompleteCallback fn = delegate(GameFramework.Resource.IResourceGroup param0, bool param1) { };
			return fn;
		}

		if(!flag)
		{
			GameFramework_Resource_UpdateResourcesCompleteCallback_Event target = new GameFramework_Resource_UpdateResourcesCompleteCallback_Event(func);
			GameFramework.Resource.UpdateResourcesCompleteCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			GameFramework_Resource_UpdateResourcesCompleteCallback_Event target = new GameFramework_Resource_UpdateResourcesCompleteCallback_Event(func, self);
			GameFramework.Resource.UpdateResourcesCompleteCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_GameFramework_Resource_UpdateResourcesCompleteCallback(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType<GameFramework.Resource.UpdateResourcesCompleteCallback>(L, pos);
	}

	void Push_GameFramework_Resource_UpdateResourcesCompleteCallback(IntPtr L, GameFramework.Resource.UpdateResourcesCompleteCallback o)
	{
		ToLua.Push(L, o);
	}

	class UnityEngine_Camera_CameraCallback_Event : LuaDelegate
	{
		public UnityEngine_Camera_CameraCallback_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Camera_CameraCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.Camera param0)
		{
			func.BeginPCall();
			func.PushSealed(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.Camera param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushSealed(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public UnityEngine.Camera.CameraCallback UnityEngine_Camera_CameraCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Camera.CameraCallback fn = delegate(UnityEngine.Camera param0) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Camera_CameraCallback_Event target = new UnityEngine_Camera_CameraCallback_Event(func);
			UnityEngine.Camera.CameraCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Camera_CameraCallback_Event target = new UnityEngine_Camera_CameraCallback_Event(func, self);
			UnityEngine.Camera.CameraCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_UnityEngine_Camera_CameraCallback(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType<UnityEngine.Camera.CameraCallback>(L, pos);
	}

	void Push_UnityEngine_Camera_CameraCallback(IntPtr L, UnityEngine.Camera.CameraCallback o)
	{
		ToLua.Push(L, o);
	}

	class UnityEngine_Application_AdvertisingIdentifierCallback_Event : LuaDelegate
	{
		public UnityEngine_Application_AdvertisingIdentifierCallback_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Application_AdvertisingIdentifierCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(string param0, bool param1, string param2)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(string param0, bool param1, string param2)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			func.EndPCall();
		}
	}

	public UnityEngine.Application.AdvertisingIdentifierCallback UnityEngine_Application_AdvertisingIdentifierCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Application.AdvertisingIdentifierCallback fn = delegate(string param0, bool param1, string param2) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Application_AdvertisingIdentifierCallback_Event target = new UnityEngine_Application_AdvertisingIdentifierCallback_Event(func);
			UnityEngine.Application.AdvertisingIdentifierCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Application_AdvertisingIdentifierCallback_Event target = new UnityEngine_Application_AdvertisingIdentifierCallback_Event(func, self);
			UnityEngine.Application.AdvertisingIdentifierCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_UnityEngine_Application_AdvertisingIdentifierCallback(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType<UnityEngine.Application.AdvertisingIdentifierCallback>(L, pos);
	}

	void Push_UnityEngine_Application_AdvertisingIdentifierCallback(IntPtr L, UnityEngine.Application.AdvertisingIdentifierCallback o)
	{
		ToLua.Push(L, o);
	}

	class UnityEngine_Application_LowMemoryCallback_Event : LuaDelegate
	{
		public UnityEngine_Application_LowMemoryCallback_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Application_LowMemoryCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call()
		{
			func.Call();
		}

		public void CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			func.EndPCall();
		}
	}

	public UnityEngine.Application.LowMemoryCallback UnityEngine_Application_LowMemoryCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Application.LowMemoryCallback fn = delegate() { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Application_LowMemoryCallback_Event target = new UnityEngine_Application_LowMemoryCallback_Event(func);
			UnityEngine.Application.LowMemoryCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Application_LowMemoryCallback_Event target = new UnityEngine_Application_LowMemoryCallback_Event(func, self);
			UnityEngine.Application.LowMemoryCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_UnityEngine_Application_LowMemoryCallback(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType<UnityEngine.Application.LowMemoryCallback>(L, pos);
	}

	void Push_UnityEngine_Application_LowMemoryCallback(IntPtr L, UnityEngine.Application.LowMemoryCallback o)
	{
		ToLua.Push(L, o);
	}

	class UnityEngine_Application_LogCallback_Event : LuaDelegate
	{
		public UnityEngine_Application_LogCallback_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Application_LogCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(string param0, string param1, UnityEngine.LogType param2)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(string param0, string param1, UnityEngine.LogType param2)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			func.EndPCall();
		}
	}

	public UnityEngine.Application.LogCallback UnityEngine_Application_LogCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Application.LogCallback fn = delegate(string param0, string param1, UnityEngine.LogType param2) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Application_LogCallback_Event target = new UnityEngine_Application_LogCallback_Event(func);
			UnityEngine.Application.LogCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Application_LogCallback_Event target = new UnityEngine_Application_LogCallback_Event(func, self);
			UnityEngine.Application.LogCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_UnityEngine_Application_LogCallback(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType<UnityEngine.Application.LogCallback>(L, pos);
	}

	void Push_UnityEngine_Application_LogCallback(IntPtr L, UnityEngine.Application.LogCallback o)
	{
		ToLua.Push(L, o);
	}

	class System_Action_bool_Event : LuaDelegate
	{
		public System_Action_bool_Event(LuaFunction func) : base(func) { }
		public System_Action_bool_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(bool param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(bool param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public System.Action<bool> System_Action_bool(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<bool> fn = delegate(bool param0) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_bool_Event target = new System_Action_bool_Event(func);
			System.Action<bool> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_bool_Event target = new System_Action_bool_Event(func, self);
			System.Action<bool> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_System_Action_bool(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType<System.Action<bool>>(L, pos);
	}

	void Push_System_Action_bool(IntPtr L, System.Action<bool> o)
	{
		ToLua.Push(L, o);
	}

	class System_Action_string_Event : LuaDelegate
	{
		public System_Action_string_Event(LuaFunction func) : base(func) { }
		public System_Action_string_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(string param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(string param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public System.Action<string> System_Action_string(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<string> fn = delegate(string param0) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_string_Event target = new System_Action_string_Event(func);
			System.Action<string> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_string_Event target = new System_Action_string_Event(func, self);
			System.Action<string> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_System_Action_string(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType<System.Action<string>>(L, pos);
	}

	void Push_System_Action_string(IntPtr L, System.Action<string> o)
	{
		ToLua.Push(L, o);
	}

	class System_Func_bool_Event : LuaDelegate
	{
		public System_Func_bool_Event(LuaFunction func) : base(func) { }
		public System_Func_bool_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public bool Call()
		{
			func.BeginPCall();
			func.PCall();
			bool ret = func.CheckBoolean();
			func.EndPCall();
			return ret;
		}

		public bool CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			bool ret = func.CheckBoolean();
			func.EndPCall();
			return ret;
		}
	}

	public System.Func<bool> System_Func_bool(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Func<bool> fn = delegate() { return false; };
			return fn;
		}

		if(!flag)
		{
			System_Func_bool_Event target = new System_Func_bool_Event(func);
			System.Func<bool> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Func_bool_Event target = new System_Func_bool_Event(func, self);
			System.Func<bool> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_System_Func_bool(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType<System.Func<bool>>(L, pos);
	}

	void Push_System_Func_bool(IntPtr L, System.Func<bool> o)
	{
		ToLua.Push(L, o);
	}

	class System_Action_UnityEngine_PhysicsScene_Unity_Collections_NativeArray_UnityEngine_ModifiableContactPair_Event : LuaDelegate
	{
		public System_Action_UnityEngine_PhysicsScene_Unity_Collections_NativeArray_UnityEngine_ModifiableContactPair_Event(LuaFunction func) : base(func) { }
		public System_Action_UnityEngine_PhysicsScene_Unity_Collections_NativeArray_UnityEngine_ModifiableContactPair_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.PhysicsScene param0, Unity.Collections.NativeArray<UnityEngine.ModifiableContactPair> param1)
		{
			func.BeginPCall();
			func.PushValue(param0);
			func.PushValue(param1);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.PhysicsScene param0, Unity.Collections.NativeArray<UnityEngine.ModifiableContactPair> param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushValue(param0);
			func.PushValue(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public System.Action<UnityEngine.PhysicsScene,Unity.Collections.NativeArray<UnityEngine.ModifiableContactPair>> System_Action_UnityEngine_PhysicsScene_Unity_Collections_NativeArray_UnityEngine_ModifiableContactPair(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<UnityEngine.PhysicsScene,Unity.Collections.NativeArray<UnityEngine.ModifiableContactPair>> fn = delegate(UnityEngine.PhysicsScene param0, Unity.Collections.NativeArray<UnityEngine.ModifiableContactPair> param1) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_UnityEngine_PhysicsScene_Unity_Collections_NativeArray_UnityEngine_ModifiableContactPair_Event target = new System_Action_UnityEngine_PhysicsScene_Unity_Collections_NativeArray_UnityEngine_ModifiableContactPair_Event(func);
			System.Action<UnityEngine.PhysicsScene,Unity.Collections.NativeArray<UnityEngine.ModifiableContactPair>> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_UnityEngine_PhysicsScene_Unity_Collections_NativeArray_UnityEngine_ModifiableContactPair_Event target = new System_Action_UnityEngine_PhysicsScene_Unity_Collections_NativeArray_UnityEngine_ModifiableContactPair_Event(func, self);
			System.Action<UnityEngine.PhysicsScene,Unity.Collections.NativeArray<UnityEngine.ModifiableContactPair>> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_System_Action_UnityEngine_PhysicsScene_Unity_Collections_NativeArray_UnityEngine_ModifiableContactPair(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType<System.Action<UnityEngine.PhysicsScene,Unity.Collections.NativeArray<UnityEngine.ModifiableContactPair>>>(L, pos);
	}

	void Push_System_Action_UnityEngine_PhysicsScene_Unity_Collections_NativeArray_UnityEngine_ModifiableContactPair(IntPtr L, System.Action<UnityEngine.PhysicsScene,Unity.Collections.NativeArray<UnityEngine.ModifiableContactPair>> o)
	{
		ToLua.Push(L, o);
	}

	class UnityEngine_AudioClip_PCMReaderCallback_Event : LuaDelegate
	{
		public UnityEngine_AudioClip_PCMReaderCallback_Event(LuaFunction func) : base(func) { }
		public UnityEngine_AudioClip_PCMReaderCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(float[] param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(float[] param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public UnityEngine.AudioClip.PCMReaderCallback UnityEngine_AudioClip_PCMReaderCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.AudioClip.PCMReaderCallback fn = delegate(float[] param0) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_AudioClip_PCMReaderCallback_Event target = new UnityEngine_AudioClip_PCMReaderCallback_Event(func);
			UnityEngine.AudioClip.PCMReaderCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_AudioClip_PCMReaderCallback_Event target = new UnityEngine_AudioClip_PCMReaderCallback_Event(func, self);
			UnityEngine.AudioClip.PCMReaderCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_UnityEngine_AudioClip_PCMReaderCallback(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType<UnityEngine.AudioClip.PCMReaderCallback>(L, pos);
	}

	void Push_UnityEngine_AudioClip_PCMReaderCallback(IntPtr L, UnityEngine.AudioClip.PCMReaderCallback o)
	{
		ToLua.Push(L, o);
	}

	class UnityEngine_AudioClip_PCMSetPositionCallback_Event : LuaDelegate
	{
		public UnityEngine_AudioClip_PCMSetPositionCallback_Event(LuaFunction func) : base(func) { }
		public UnityEngine_AudioClip_PCMSetPositionCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(int param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(int param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public UnityEngine.AudioClip.PCMSetPositionCallback UnityEngine_AudioClip_PCMSetPositionCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.AudioClip.PCMSetPositionCallback fn = delegate(int param0) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_AudioClip_PCMSetPositionCallback_Event target = new UnityEngine_AudioClip_PCMSetPositionCallback_Event(func);
			UnityEngine.AudioClip.PCMSetPositionCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_AudioClip_PCMSetPositionCallback_Event target = new UnityEngine_AudioClip_PCMSetPositionCallback_Event(func, self);
			UnityEngine.AudioClip.PCMSetPositionCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_UnityEngine_AudioClip_PCMSetPositionCallback(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType<UnityEngine.AudioClip.PCMSetPositionCallback>(L, pos);
	}

	void Push_UnityEngine_AudioClip_PCMSetPositionCallback(IntPtr L, UnityEngine.AudioClip.PCMSetPositionCallback o)
	{
		ToLua.Push(L, o);
	}

	class System_Action_UnityEngine_AsyncOperation_Event : LuaDelegate
	{
		public System_Action_UnityEngine_AsyncOperation_Event(LuaFunction func) : base(func) { }
		public System_Action_UnityEngine_AsyncOperation_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.AsyncOperation param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.AsyncOperation param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public System.Action<UnityEngine.AsyncOperation> System_Action_UnityEngine_AsyncOperation(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<UnityEngine.AsyncOperation> fn = delegate(UnityEngine.AsyncOperation param0) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_UnityEngine_AsyncOperation_Event target = new System_Action_UnityEngine_AsyncOperation_Event(func);
			System.Action<UnityEngine.AsyncOperation> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_UnityEngine_AsyncOperation_Event target = new System_Action_UnityEngine_AsyncOperation_Event(func, self);
			System.Action<UnityEngine.AsyncOperation> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_System_Action_UnityEngine_AsyncOperation(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType<System.Action<UnityEngine.AsyncOperation>>(L, pos);
	}

	void Push_System_Action_UnityEngine_AsyncOperation(IntPtr L, System.Action<UnityEngine.AsyncOperation> o)
	{
		ToLua.Push(L, o);
	}

}

